{
"name": "Build APK",
"on": ["push", "workflow_dispatch"],
"jobs": {
"build": {
"runs-on": "ubuntu-latest",
"steps": [
{"uses": "actions/checkout@v4"},
{"uses": "actions/setup-java@v4", "with": {"distribution": "temurin", "java-version": "21"}},
{"uses": "gradle/actions/setup-gradle@v4", "with": {"gradle-version": "9.3.1"}},
{"name": "Licences", "run": "yes | \"$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager\" --licenses || true"},
{"name": "Build", "run": "D=$(dirname \"$(find . -name settings.gradle.kts | head -n 1)\") && echo \"Projet trouve dans : $D\" && cd \"$D\" && ( [ -f debug.keystore ] || keytool -genkeypair -keystore debug.keystore -storepass android -keypass android -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -dname \"CN=Android Debug,O=Android,C=US\" ) && gradle assembleDebug --no-daemon"},
{"uses": "actions/upload-artifact@v4", "with": {"name": "Scolaris-APK", "path": "**/build/outputs/apk/debug/*.apk"}}
]
}
}
}
